# docker-compose version
version: "3.8"

#container list
services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - /home/ubuntu/trendit/certbot-etc:/etc/letsencrypt
    networks:
      - app-network
volumes:
  certbot-etc:
networks:
  app-network:
    driver: bridge
